"""
Child Bot — Generated by Master Bot
"""

import asyncio
import logging
import json
import os
import sys

from telegram import Update
from telegram.ext import (
    Application,
    CommandHandler,
    MessageHandler,
    filters,
    ContextTypes,
    ConversationHandler,
)
from telethon import TelegramClient, events

# ── Config from environment ──────────────────
BOT_TOKEN          = os.environ.get("BOT_TOKEN", "")
API_ID             = int(os.environ.get("API_ID", "0"))
API_HASH           = os.environ.get("API_HASH", "")
RESET_BOT_USERNAME = os.environ.get("RESET_BOT_USERNAME", "")
SESSION_NAME       = os.environ.get("SESSION_NAME", "session")
RESPONSE_TIMEOUT   = int(os.environ.get("RESPONSE_TIMEOUT", "30"))
CREDITS            = os.environ.get("CREDITS", "")
OWNERS_RAW         = os.environ.get("OWNER_IDS", "")
OWNER_IDS          = [int(x.strip()) for x in OWNERS_RAW.split(",") if x.strip()]
SESSIONS_FILE      = os.environ.get("SESSIONS_FILE", "sessions.json")
# ────────────────────────────────────────────

logging.basicConfig(
    format="%(asctime)s | %(levelname)s | %(message)s",
    level=logging.INFO
)
logger = logging.getLogger(__name__)

if sys.platform == "win32":
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

pending_responses: dict[int, asyncio.Future] = {}
WAITING_LOGIN = 1
telethon_client: TelegramClient = None


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Sessions Manager
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
def load_sessions() -> dict:
    if os.path.exists(SESSIONS_FILE):
        with open(SESSIONS_FILE, "r") as f:
            return json.load(f)
    return {"credentials": {}, "sessions": {}}

def save_sessions(data: dict):
    with open(SESSIONS_FILE, "w") as f:
        json.dump(data, f, indent=2)

def is_logged_in(user_id: int) -> bool:
    return str(user_id) in load_sessions().get("sessions", {})

def login_user(user_id: int, username: str):
    data = load_sessions()
    data.setdefault("sessions", {})[str(user_id)] = {"username": username}
    save_sessions(data)

def logout_user(user_id: int):
    data = load_sessions()
    data.get("sessions", {}).pop(str(user_id), None)
    save_sessions(data)

def get_credentials(login: str):
    return load_sessions().get("credentials", {}).get(login.upper())

def add_credential(login: str, password: str):
    data = load_sessions()
    data.setdefault("credentials", {})[login.upper()] = {"password": password}
    save_sessions(data)

def remove_credential(login: str):
    data = load_sessions()
    data.get("credentials", {}).pop(login.upper(), None)
    save_sessions(data)

def is_owner(user_id: int) -> bool:
    return user_id in OWNER_IDS


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Access Guard
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
async def require_login(update: Update) -> bool:
    if is_logged_in(update.effective_user.id):
        return True
    await update.message.reply_text(
        "🔐 *Authorization Required*\n\n"
        "You are not logged in.\n"
        "▸ /login to access this service.\n\n"
        f"💬 Support · {CREDITS}",
        parse_mode="Markdown",
    )
    return False


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Telethon — Reset Bot Bridge
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
async def send_to_reset_bot(key: str) -> str | None:
    global telethon_client
    loop = asyncio.get_event_loop()
    future: asyncio.Future = loop.create_future()
    sent_msg = None

    async def handler(event):
        reply_to = event.message.reply_to_msg_id
        if reply_to in pending_responses:
            f = pending_responses[reply_to]
            if not f.done():
                f.set_result(event.message.text)

    telethon_client.add_event_handler(
        handler,
        events.NewMessage(from_users=RESET_BOT_USERNAME)
    )

    try:
        sent_msg = await telethon_client.send_message(RESET_BOT_USERNAME, f"/reset {key}")
        pending_responses[sent_msg.id] = future
        return await asyncio.wait_for(future, timeout=RESPONSE_TIMEOUT)
    except asyncio.TimeoutError:
        return None
    except Exception as e:
        logger.error(f"❌ Reset error: {e}")
        return None
    finally:
        if sent_msg:
            pending_responses.pop(sent_msg.id, None)
        telethon_client.remove_event_handler(handler)


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# /start
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
async def cmd_start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user = update.effective_user
    logged = is_logged_in(user.id)
    status   = "🟢 Active Session"    if logged else "🔴 Not Authenticated"
    next_step = "/start to submit a key" if logged else "/login to get started"
    await update.message.reply_text(
        f"👋 Welcome, *{user.first_name}*\n\n"
        f"⚡ *Reset System*\n\n"
        f"🔐 Status · {status}\n"
        f"▸ {next_step}\n"
        f"▸ /help for all commands\n\n"
        f"💬 {CREDITS}",
        parse_mode="Markdown",
    )


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# /help
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
async def cmd_help(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(
        "📋 *Commands*\n\n"
        "🔓 *Account*\n"
        "▸ /login — Authenticate\n"
        "▸ /logout — End session\n\n"
        "⚡ *Services*\n"
        "▸ /start `<key>` — Submit reset key\n\n"
        "📌 *Example*\n"
        "`/start XYA0QWTP7ID34WP3`\n\n"
        f"💬 {CREDITS}",
        parse_mode="Markdown",
    )


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# /login
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
async def cmd_login(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if is_logged_in(update.effective_user.id):
        await update.message.reply_text(
            "✅ *Already Logged In*\n\n"
            "Your session is active.\n"
            "▸ /start to submit a key\n"
            "▸ /logout to end session",
            parse_mode="Markdown",
        )
        return ConversationHandler.END
    await update.message.reply_text(
        "🔐 *Login*\n\n"
        "Send your credentials on two lines:\n\n"
        "`LOGIN`\n`PASSWORD`\n\n"
        "🔒 _Secured · /cancel to abort_",
        parse_mode="Markdown",
    )
    return WAITING_LOGIN

async def receive_credentials(update: Update, context: ContextTypes.DEFAULT_TYPE):
    lines = update.message.text.strip().split("\n")
    if len(lines) < 2:
        await update.message.reply_text(
            "⚠️ *Incorrect Format*\n\n"
            "Send credentials on two lines:\n\n"
            "`LOGIN`\n`PASSWORD`\n\n"
            "_Try again or /cancel_",
            parse_mode="Markdown",
        )
        return WAITING_LOGIN
    login, password = lines[0].strip(), lines[1].strip()
    cred = get_credentials(login)
    if cred and cred["password"] == password:
        login_user(update.effective_user.id, login)
        await update.message.reply_text(
            "✅ *Login Successful*\n\n"
            f"Welcome, *{login}* 👋\n\n"
            "▸ /start to submit a reset key",
            parse_mode="Markdown",
        )
        return ConversationHandler.END
    await update.message.reply_text(
        "❌ *Login Failed*\n\n"
        "Incorrect credentials. Please try again.\n\n"
        f"💬 {CREDITS}",
        parse_mode="Markdown",
    )
    return WAITING_LOGIN

async def cancel_login(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("↩️ *Login Cancelled*", parse_mode="Markdown")
    return ConversationHandler.END


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# /logout
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
async def cmd_logout(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not is_logged_in(update.effective_user.id):
        await update.message.reply_text(
            "⚠️ *No Active Session*\n\n"
            "You are not logged in.\n"
            "▸ /login to authenticate",
            parse_mode="Markdown",
        )
        return
    logout_user(update.effective_user.id)
    await update.message.reply_text(
        "👋 *Logged Out Successfully*\n\n"
        "Your session has been terminated.\n"
        "▸ /login to sign back in",
        parse_mode="Markdown",
    )


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# /start
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
async def cmd_fluorite(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not await require_login(update):
        return
    args = context.args
    if not args:
        await update.message.reply_text(
            "📌 *Usage*\n\n"
            "`/start YOUR_KEY`\n\n"
            "📎 Example:\n"
            "`/start XYA0QWTP7ID34WP3`\n\n"
            "⚠️ _Key must be 16 alphanumeric characters_",
            parse_mode="Markdown",
        )
        return
    key = args[0].upper().strip()
    if not key.isalnum() or len(key) != 16:
        await update.message.reply_text(
            "❌ *Invalid Key*\n\n"
            f"Received: `{key}`\n\n"
            "▸ Must be exactly *16 characters*\n"
            "▸ Letters and numbers only",
            parse_mode="Markdown",
        )
        return
    user = update.effective_user
    logger.info(f"👤 ({user.id}) → request")
    wait_msg = await update.message.reply_text(
        "⏳ *Processing your request...*\n\n"
        f"🔑 Key · `{key}`",
        parse_mode="Markdown",
    )
    raw_response = await send_to_reset_bot(key)
    await wait_msg.delete()
    if raw_response is None:
        await update.message.reply_text(
            "⏱ *Request Timed Out*\n\n"
            f"🔑 Key · `{key}`\n\n"
            f"No response within *{RESPONSE_TIMEOUT}s*. Please try again.\n\n"
            f"💬 {CREDITS}",
            parse_mode="Markdown",
        )
    else:
        try:
            await update.message.reply_text(raw_response, parse_mode="Markdown")
        except Exception:
            await update.message.reply_text(raw_response)


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Owner Commands
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
async def cmd_addaccount(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not is_owner(update.effective_user.id):
        await update.message.reply_text("🚫 *Owner only.*", parse_mode="Markdown")
        return
    args = context.args
    if len(args) < 2:
        await update.message.reply_text("⚠️ *Usage:* `/addaccount LOGIN PASSWORD`", parse_mode="Markdown")
        return
    login, password = args[0].upper(), args[1]
    add_credential(login, password)
    await update.message.reply_text(
        "✅ *Account Created*\n\n"
        f"👤 Login · `{login}`\n"
        f"🔑 Password · `{password}`",
        parse_mode="Markdown",
    )

async def cmd_removeaccount(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not is_owner(update.effective_user.id):
        await update.message.reply_text("🚫 *Owner only.*", parse_mode="Markdown")
        return
    args = context.args
    if not args:
        await update.message.reply_text("⚠️ *Usage:* `/removeaccount LOGIN`", parse_mode="Markdown")
        return
    login = args[0].upper()
    remove_credential(login)
    await update.message.reply_text(
        f"🗑️ *Account Removed*\n\n`{login}` has been deleted.",
        parse_mode="Markdown",
    )

async def cmd_listaccounts(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not is_owner(update.effective_user.id):
        await update.message.reply_text("🚫 *Owner only.*", parse_mode="Markdown")
        return
    data = load_sessions()
    creds = data.get("credentials", {})
    if not creds:
        await update.message.reply_text("📋 *No accounts registered yet.*", parse_mode="Markdown")
        return
    lines = ["📋 *Registered Accounts*\n"]
    for i, login in enumerate(creds.keys(), 1):
        lines.append(f"`{i}.` 👤 `{login}`")
    await update.message.reply_text("\n".join(lines), parse_mode="Markdown")


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Main
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
async def main():
    global telethon_client

    if not os.path.exists(SESSIONS_FILE):
        save_sessions({"credentials": {}, "sessions": {}})

    # Connect Telethon using existing session
    telethon_client = TelegramClient(SESSION_NAME, API_ID, API_HASH)
    await telethon_client.connect()
    if not await telethon_client.is_user_authorized():
        logger.error("❌ Telethon session not found! Run setup_session.py first.")
        return

    logger.info(f"✅ Child bot ready | bot started")

    app = Application.builder().token(BOT_TOKEN).build()

    login_conv = ConversationHandler(
        entry_points=[CommandHandler("login", cmd_login)],
        states={WAITING_LOGIN: [MessageHandler(filters.TEXT & ~filters.COMMAND, receive_credentials)]},
        fallbacks=[CommandHandler("cancel", cancel_login)],
    )
    app.add_handler(login_conv)
    app.add_handler(CommandHandler("start",         cmd_start))
    app.add_handler(CommandHandler("help",          cmd_help))
    app.add_handler(CommandHandler("logout",        cmd_logout))
    app.add_handler(CommandHandler("fluorite",      cmd_fluorite))
    app.add_handler(CommandHandler("addaccount",    cmd_addaccount))
    app.add_handler(CommandHandler("removeaccount", cmd_removeaccount))
    app.add_handler(CommandHandler("listaccounts",  cmd_listaccounts))

    async with app:
        await app.initialize()
        await app.start()
        await app.updater.start_polling(drop_pending_updates=True)
        await asyncio.Event().wait()
        await app.updater.stop()
        await app.stop()

    await telethon_client.disconnect()


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        pass
